<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class MedHistory extends Model
{
    use HasFactory;
    protected $state = 'med_histories';
    protected $fillable = [
        'informant',
        'date_of_anamnesis',
        'student_id',
        'appraisal',
        'have_caregiver',
        'have_AEE',
        'turn_AEE',
        'not_study_justify',
        'name_mother',
        'date_mother',
        'rg_mother',
        'profession_mother',
        'cellphone_mother',
        'name_father',
        'date_father',
        'rg_father',
        'profession_father',
        'cellphone_father',
        'address',
        'have_medication',
        'what_medication',
        'compplaint',
        'who_lives',
        'state_parents_relation',
        'time_state_relation',
        'new_relation_mother',
        'time_new_relation_mother',
        'lives_together_new_relation_mother',
        'new_relation_father',
        'time_new_relation_father',
        'lives_together_new_relation_father',
        'have_kinship_parents',
        'what_kinship_parents',
        'have_child_desired',
        'gestation_order',
        'number_children',
        'history_abort',
        'abort_justify',
        'child_adopted',
        'have_pre_natal',
        'time_gestation',
        'type_childbirth',
        'have_disease_gestation',
        'what_disease_gestation',
        'have_treatment',
        'place_birth',
        'have_problems_birth',
        'what_problems_birth',
        'have_discharged_together',
        'detail_discharged_together',
        'have_neonatal_tests',
        'result_neonatal_tests',
        'detail_neonatal_tests',
        'have_mother_breastfeed',
        'have_nozzle',
        'detail_nozzle',
        'have_delay_NPM',
        'detail_delay_NPM',
        'have_normal_development',
        'detail_normal_development',
        'have_desfrald_yet',
        'age_desfrald_yet',
        'have_sphincters_control',
        'age_sphincters_control',
        'bites_nails',
        'hurt_yourself',
        'state_sleep',
        'sleeps_in_separate',
        'sleep_time',
        'difficulty_waking_up',
        'independent_daily_activities',
        'other_difficulty',
        'child_temperament',
        'stubbornness',
        'tantrum',
        'lies',
        'aggressiveness',
        'shyness',
        'affectionate',
        'inappropriate_behavior',
        'how_manifests_inappropriate_behavior',
        'tics_manias',
        'hyperfocus',
        'waiting_skill',
        'tolerates_frustration',
        'responds_orders',
        'sexual_curiosity',
        'how_manifests_sexual_curiosity',
        'daily_routine',
        'rigidity_daily_routine',
        'what_daily_routine',
        'sports_activity',
        'what_sports_activity',
        'age_start_school',
        'how_school_adaptation',
        'have_difficulty_learning',
        'justify_difficulty_learning',
        'school_reinforcement',
        'parents_participate_school_life',
        'favorite_activity_school',
        'complaint_behavior',
        'demonstrates_satisfaction_school',
        'report_situation_school_in_home',
        'knows_handle_pencil',
        'reading_letters',
        'reading_words',
        'reading_texts',
        'do_activities_autonomously',
        'not_participate_collective_activities',
        'follows_school_routine',
        'adapted_activities',
        'literacy_level',
        'have_allergy',
        'what_allergy',
        'wear_glasses',
        'use_hearing_aid',
        'know_libras',
        'have_therapeutic',
        'times_days_therapeutic',
        'history_disorders_family',
        'what_history_disorders_family',
        'have_update_vaccines',
        'detail_update_vaccines',
        'relation_family_members',
        'super_protected',
        'have_access_cellphone',
        'time_access_cellphone',
        'accompanies_access_cellphone',
        'already_had_information_institution',
        'who_recommend_institution',
        'participate_contribution',
        'general_observations',
        'signature'
    ];
    protected $casts = [
        'have_caregiver' => 'boolean',
        'have_AEE' => 'boolean',
        'have_medication' => 'boolean',
        'have_kinship_parents' => 'boolean',
        'new_relation_mother' => 'boolean',
        'new_relation_father' => 'boolean',
        'have_disease_gestation' => 'boolean',
        'have_discharged_together' => 'boolean',
        'have_problems_birth' => 'boolean',
        'have_neonatal_tests' => 'boolean',
        'have_nozzle' => 'boolean',
        'have_delay_NPM' => 'boolean',
        'have_normal_development' => 'boolean',
        'have_desfrald_yet' => 'boolean',
        'have_sphincters_control' => 'boolean',
        'stubbornness' => 'boolean',
        'tantrum' => 'boolean',
        'lies' => 'boolean',
        'inappropriate_behavior' => 'boolean',
        'aggressiveness' => 'boolean',
        'shyness' => 'boolean',
        'affectionate' => 'boolean',
        'sexual_curiosity' => 'boolean',
        'tics_manias' => 'boolean',
        'hyperfocus' => 'boolean',
        'waiting_skill' => 'boolean',
        'sports_activity' => 'boolean',
        'tolerates_frustration' => 'boolean',
        'responds_orders' => 'boolean',
        'daily_routine' => 'boolean',
        'have_difficulty_learning' => 'boolean',
        'have_allergy' => 'boolean',
        'have_therapeutic' => 'boolean',
        'history_disorders_family' => 'boolean',
        'have_update_vaccines' => 'boolean',
        'have_access_cellphone' => 'boolean',
        'already_had_information_institution' => 'boolean',
    ];

    public function student(): BelongsTo
    {
        return $this->belongsTo(Student::class, 'student_id');
    }
}
